# Generated by Django 4.2.11 on 2025-09-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('improvement', 'Improvement'), ('documentation', 'Documentation'), ('backend', 'Backend'), ('frontend', 'Frontend')], max_length=50, unique=True),
        ),
    ]
